name: LINE Notify example
on:
  issues:
    types: opened
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            이슈가 등록 되었습니다.
            ${{ github.event.issue.title }}
